server:
  port: ${PORT:8088}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
               
spring:
  devtools:
    livereload:
      enabled: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-id
          uri: lb://FEE-SERVICE
          predicates:
            - Path=/api/fee/**
          filters:
            - StripPrefix=1
        - id: studentService
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**      discovery:        locator:          enabled: true          lower-case-service-id: true       
  
  

  