server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
               
  server:
    enableSelfPreservation: false
    
spring:  devtools:    livereload:      enabled: true
  application:    name: fee-service
    
resilience4j:
  retry:
    instances:
      studentSearch:
        max-attempts: 4
        waitDuration: 2s
      throwingException:
        max-attempts: 2
        waitDuration: 2s
        retryExceptions:
          - java.lang.Exception
