server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
               
  server:
    enableSelfPreservation: false
    
spring:  devtools:    livereload:      enabled: true
  application:    name: fee-service
